### ISSUE TITLE
shoulda:list rake task is not working in Rails 3 with Ruby 1.9.2

### ISSUE THREAD

**Issue by contentfree** [thoughtbot/shoulda#115]
The error is:
    rake aborted!
    undefined method `run=' for Test::Unit:Module
    /Users/dave/.rvm/gems/ruby-1.9.2-head/gems/shoulda-2.11.1/lib/shoulda/tasks/list_tests.rake:11:in`block (2 levels) in <top (required)>'

Switching to 1.8.7-p249 "fixes" it.
