### ISSUE TITLE
method not found with Rails 3.1.0RC1

### ISSUE THREAD

**Issue by davidsf** [thoughtbot/shoulda#171]
I have updated an app to Rails 3.1.0RC1 and the tests now give the error: 

undefined method `have_many' for UserTest:Class (NoMethodError)

with all the shoulda matchers. Is like doesn't load shoulda but I have require 'shoulda' in test_helper.rb and require 'test_helper.rb' in the test file (the same test works with Rails 3.0.x).  

Rails 3.1.0.rc1 with shoulda 2.11.3
