### ISSUE TITLE
undefined method `validate_presence_of' in shoulda 3.0.1, Rails  3.2 and RSpec-Rails 2.8.1

### ISSUE THREAD

**Issue by domness** [thoughtbot/shoulda#203]
Seem to be unable to fix an error saying:

```
Failure/Error: it { should validate_presence_of(:username) }
 NoMethodError:
   undefined method `validate_presence_of' for #<RSpec::Core::ExampleGroup::Nested_2::Nested_1:0x007fee4f3aa9b8>
```

Also using ruby-1.9.2

**Comment by adham90** [comment]
hey, i have the same error with rails '4.2.0' & shoulda-matchers 2.7.0 & rspec-rails 3.1.0

**Comment by veetase** [comment]
Having the same error with rails '4.2.0' & shoulda-matchers 2.8.0 & rspec-rails 3.1.0

**Comment by amitdotagarwal** [comment]
try to include include ActiveModel::Validations::Callbacks in your model

**Comment by mockdeep** [comment]
I was able to resolve this in another project by adding `gem 'shoulda-matchers', require: false` to the `Gemfile`, and then inside of `spec_helper` adding `require 'shoulda/matchers'`.

**Comment by realdlee** [comment]
I was having the same error on Rails 3.2 and shoulda-matcher 2.7.0 and @mockdeep's fix resolved it for me.

**Comment by collimarco** [comment]
Same problem here with Rails 4.2, shoulda-matchers 2.8.0, rspec 3.2.

```
  3) User 
     Failure/Error: it { is_expected.to validate_presence_of :email }
     NoMethodError:
       undefined method `validate_presence_of' for #<RSpec::ExampleGroups::User:0x007fc072785e30>
     # ./spec/models/user_spec.rb:5:in `block (2 levels) in <top (required)>'
```

None of the following solutions have worked for me:
- downgrade to shoulda-matchers  2.5
- using require 'shoulda/matchers' or  require 'shoulda-matchers' 
- move the gem around in test group

Here's my Gemfile:

```
source 'https://rubygems.org'
gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'foundation-rails'
gem 'haml'
gem 'haml-rails' 
gem 'devise'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'

  gem 'rspec-rails', '~> 3.0'
  gem 'capybara'
  gem 'factory_girl_rails'
end

gem 'shoulda-matchers', require: false, group: :test
```

and my spec_helper.rb:

```
require 'capybara/rspec'
require 'factory_girl_rails'
require 'shoulda/matchers'

RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
```

**Comment by collimarco** [comment]
After some hours of research here's a solution that worked for me.

    require 'shoulda/matchers'

should go **after**

    require 'rspec/rails'

in `rails_helper.rb`(not at the top of `spec_helper.rb`).

**Comment by mgathu1** [comment]
I had the same error and @mockdeep solution resolved fot me also. Running rails 4.2 with rspec 3.2, shoulda-matchers 2.8.0

**Comment by stefanhendriks** [comment]
Running into this problem as well and no solution found. (running Rails 4.2, Rspec 3.2 and shoulda-matchers 2.8.0)

What I did so far (project setup):
- create new rails app
- set up `rails-rspec`
- run `rspec generate:install`
- add `shoulda-matchers`
- boom!

*Solutions I tried*:
- move gem to separate test group
- `require 'shoulda/matchers'` or `'shoulda-matchers'` *after* `rspec/rails`
- downgrade to shoulda-matchers 2.5.0
- use `require:false` in `Gemfile`

*Gemfile*
```
source 'https://rubygems.org'

gem 'rails', '~> 4.2.0'
gem 'pg', '0.15.1' # postgres
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :test do
  gem 'shoulda-matchers', require: false
end

group :test, :development do
  gem 'rspec-rails'
end
```

*rails_helper*:
```
# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV['RAILS_ENV'] ||= 'test'
require 'spec_helper'
require File.expand_path('../../config/environment', __FILE__)
require 'rspec/rails'
require 'shoulda/matchers'

Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }

ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true
  config.infer_spec_type_from_file_location!
end
```

*spec_helper*:
```
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
```

*spec*:
```
require 'rails_helper'

# Developer extends from ActiveRecord::Base
describe Developer do
  validates_presence_of :name
end
```

*Output*:
```
```

**Comment by stefanhendriks** [comment]
Looks like I can reproduce this using `suspenders` as well (from a brand new project).

**Comment by andyw8** [comment]
@stefanhendriks - the shoulda-matches method is `validate_presence_of`, not `validates_presence_of. And I'm pretty sure it needs to be within an `it` block, i.e.:

```ruby
describe Developer do
  it { should validate_presence_of(:name) }
end
```

**Comment by stefanhendriks** [comment]
OMG i can't believe I missed that. It works now, thanks!

**Comment by prodigerati** [comment]
#gemfile

    group :test do
      gem 'shoulda-matchers', require: false
    end

fixed it for me, thanks.

**Comment by elle** [comment]
Not sure if the same issue, but getting the same error.

My set up is
* RSpec 3.3 
* Sinatra 1.4.6

```
# spec/spec_helper.rb
require "shoulda/matchers"

# Gemfile
group :development, :test do
  gem "byebug"
  gem "database_cleaner"
  gem "factory_girl"
  gem "launchy"
  gem "rspec"
  gem "shoulda-matchers", require: false
end
```

If I use `shoulda-matchers` version 2.8x and below, specs pass.
`shoulda-matchers` version 3.3.0 and I get the same error:
`undefined method `validate_presence_of' for #<RSpec::ExampleGroups::Post:0x007fd51c13cc40>`

**Comment by mosinski** [comment]
Today, I am trying to use gem in rails, but still got this error.
Even changing version to 2.8.0 did not help in my case.

```
#Gemfile
group :test do
  gem 'factory_girl_rails'
  gem 'shoulda-matchers', require: false
  gem 'rspec-rails'
  gem 'simplecov'
end

#spec/spec_helper.rb
require 'shoulda/matchers'

#spec/models/user_spec.rb 
require "rails_helper"

describe User do
  it { should validate_presence_of(:email) }
end
```

**Error:**
```
undefined method `validate_presence_of' for #<RSpec::ExampleGroups::User:0x0000000589d0c8>
```
**My set up:**
- rails 4.2.1
- shoulda-matchers 3.0.0 tested 2.8.0
- rspec-rails 3.3.3
- rails-api 0.4.0

**Comment by zekefast** [comment]
Same here:

- Ruby: `2.2.3`,
- RSpec: `3.3.0`
- ActiveRecord: `4.2.4`
- ActiveModel: `4.2.4`

it works for `2.8.0` and does not work with `3.0.0`.

### Configuration for `2.8.0`

```ruby
# Gemfile
group :test do
    gem "shoulda-matchers", "< 3.0.0",
    require: false
end
```

```ruby
# spec/spec_helper.rb

# no require of rails or active record, suppose this loads them
require "bundler/setup"
::Bundler.require(:default, :test)

require "shoulda-matchers"
```

### Configuration for `3.0.0`

```ruby
# Gemfile
group :test do
  gem "shoulda-matchers", ">= 3.0.0",
    require: false
end
```
```ruby
# spec/spec_helper.rb

# no require of rails or active record, suppose this loads them
require "bundler/setup"
::Bundler.require(:default, :test)

require "shoulda/matchers"
::Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    #with.test_framework :minitest
    #with.test_framework :minitest_4
    #with.test_framework :test_unit

    # Choose one or more libraries:
    with.library :active_record
    with.library :active_model
    #with.library :action_controller
    # Or, choose the following (which implies all of the above):
    #with.library :rails
  end
end

RSpec.configure do |config|
  # ...
end
```

**Comment by karlingen** [comment]
+1 same here

**Comment by wbigal** [comment]
+1

**Comment by zekefast** [comment]
@karlingen, @wbigal The issue was fixed for me, by adding `type: :model` tag to tests. More details [here](https://github.com/thoughtbot/shoulda-matchers/issues/797#issuecomment-146408263).

**Comment by wbigal** [comment]
It works for me:
```ruby
# spec/spec_helper.rb
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```
```ruby
# spec/models/post_spec.rb
RSpec.describe Post, type: :model do
   it { should validate_presence_of(:title) }
end
```

Thanks @zekefast

**Comment by karlingen** [comment]
Thanks @wbigal

**Comment by brianjlandau** [comment]
This should be reopened IMO.

I'm running

Ruby: 2.2.3
Rails: 4.2.4
rspec: 3.3.0
rspec-rails: 3.3.3
shoulda-matcher: 3.0.0

`Gemfile`:

```ruby
source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails', '~> 4.2.4'

# other gems ...

group :test do
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'simplecov', require: false
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end
```

`spec/rails_helper.rb`:

```ruby
ENV["RAILS_ENV"] ||= 'test'

require 'simplecov' if ENV['COV']

require 'spec_helper'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'shoulda/matchers'
require 'capybara/rspec'

# This line has the downside of increasing the boot-up time by
# auto-requiring all files in the support directory.
# Alternatively, in the individual `*_spec.rb` files, manually
# require only the support files necessary.
#
Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}

# Checks for pending migrations before tests are run.
# If you are not using ActiveRecord, you can remove this line.
ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|
  config.use_transactional_fixtures = true
  config.infer_base_class_for_anonymous_controllers = false
  config.infer_spec_type_from_file_location!

  config.include FactoryGirl::Syntax::Methods
  config.include Capybara::DSL
end

suppress_warnings { BCrypt::Engine::DEFAULT_COST = 4 }
```

Model file (`app/models/foo.rb`):

```ruby
class Foo
  include ActiveModel::Model

  attr_accessor :title, :body

  validates :title, presence: true

end
```

Model spec (`spec/models/foo_spec.rb`):

```ruby
require 'rails_helper'

RSpec.describe Foo, type: :model do
  it { should validate_presence_of(:title) }
end
```

Output from running `bundle exec rake spec`:

```
     Failure/Error: it { should validate_presence_of(:title) }
     NoMethodError:
       undefined method `validate_presence_of' for #<RSpec::ExampleGroups::Foo:0x007f99d61d1268>
     # ./spec/models/foo_spec.rb:4:in `block (2 levels) in <top (required)>'
```

Adding `require: false` to the `Gemfile` did not help. I am not using TestUnit or any other testing framework.

Please advise.

**Comment by bo-oz** [comment]
Solution of @wbigal fixed it for me!

**Comment by brianjlandau** [comment]
Ah, thanks! Didn't realize you **had** to add the config. I thought without it, it would still automagically configure it properly. My bad.

**Comment by otaviomedeiros** [comment]
Solution of @zekefast and @wbigal just worked for me!
Thanks!

**Comment by dladowitz** [comment]
Thanks @zekefast. You're solution of adding to spec_helper.rb fixed my issue!

**Comment by DonGiulio** [comment]
I had the same issue, various solutions combined fixed it form me, here's a summary:

I created `spec/shoulda_helper.rb` file with the following content (good for my environment): 

      require 'shoulda/matchers'

      Shoulda::Matchers.configure do |config|
        config.integrate do |with|
          # Choose a test framework:
          with.test_framework :rspec
          # with.test_framework :minitest
          # with.test_framework :minitest_4
          # with.test_framework :test_unit

          # Choose one or more libraries:
          # with.library :active_record
          # with.library :active_model
          # with.library :action_controller
          # Or, choose the following (which implies all of the above):
          with.library :rails
        end
      end

I added to `spec/rails_helper.rb` after the `require 'rspec/rails'` the line: 

     require 'shoulda_helper'

my `Gemfile` has:

    group :development, :test do
      gem 'rspec-rails'
    end

    group :test do
      gem 'shoulda-matchers'
    end

it actually works also if I place shoulda in development, and regardless the: `require: false`, I placed shoulda in test because I don't think I'll ever need in dev.

**Comment by nmenag** [comment]
i had the same problem, i resolved with http://matchers.shoulda.io/docs/v3.0.1/

**Comment by jacobmitchinson** [comment]
Thanks @wbigal

**Comment by thiensubs** [comment]
Thanks @DonGiulio

**Comment by icemall** [comment]
Thanks @wbigal

**Comment by Khovanov** [comment]
Thanks @zekefast

**Comment by zekefast** [comment]
@Khovanov You are welcome!

**Comment by bsodmike** [comment]
After everything, it still wouldn't work in Rails 4.2+.  I had to add `type: :model`.

```ruby
RSpec.describe Foo, type: :model do
```

**Comment by kvokka** [comment]
rails 4.2.4
shoulda matchers 3.0.1
all fixes after adding to ```spec\spec_helper.rb```
```
require "bundler/setup"
::Bundler.require(:default, :test)
require "shoulda/matchers"
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

**Comment by brunojppb** [comment]
+1 @kvokka. Thanks!!!

**Comment by nurulazradm** [comment]
+1 @zekefast. Thanks!!!

works on Rails 4.2.3, Ruby 2.2.2, RSpec 3.3.2 and Shoulda-Matchers 3.0.1

**Comment by Joseworks** [comment]
Thank you @kvokka. That was driving me nuts. Ruby 2.2.3 Rails 4.2.3

**Comment by juniormesquitadandao** [comment]
Setting for rails 4.2.5 and ruby 2.2.4

Gemfile
```ruby
group :test do
  gem 'shoulda-matchers', '~> 3.0'
end
```
spec/shoulda_matchers_helper.rb
```ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```
spec/rails_helper.rb
```ruby
require 'spec_helper'
require 'shoulda_matchers_helper'
require 'rspec/rails'
```

**Comment by AlexSandiyarov** [comment]
@juniormesquitadandao Thx!!!

but you put into spec/rails_helper.rb lite bug

```
require 'spec_helper'
require 'shoulda_matche**# r**s_helper'
require 'rspec/rails'
```

**Comment by AlexSandiyarov** [comment]
# ****

**Comment by kesha-antonov** [comment]
Thanks @kvokka Completely forgot to add this!

**Comment by variousred** [comment]
I'm having to include 
```require 'active_support/test_case'
require 'action_controller'
``` in my `rails_helper.rb` in order to get this to work

```ruby-2.2.2/gems/shoulda-matchers-3.1.1
ruby-2.2.2/gems/rspec-3.4.0
ruby-2.2.2/gems/rails-4.1.14.1```

**Comment by monteirobrena** [comment]
@kvokka thank you!!!

Rails 4.2.3
ruby 2.0.0p481 
RSpec 3.4.2
shoulda-matchers 3.1.1

**Comment by olivierlacan** [comment]
I'm confused why this issue has been going for so long and through so many different versions of the gem and Rails. I see people doing some weird require order hacking in order to get it to work. I used @bsodmike's trick (`RSpec.describe Foo, type: :model do`) but effectively in Rails 4.2.6 with the latest version (3.1.1), this gem is broken by default.

**Comment by jvenezia** [comment]
+1 @kvokka 

This should be fixed or documented.

**Comment by bsodmike** [comment]
Hi all,

Just to confirm, I've got the following in a Rails 5 app,

- rails 5.0.0.beta3)
- rspec-rails (3.5.0.pre)
- shoulda-matchers (3.0.1)

And this worked just fine without `type: :model`.

FYI to get [rspec-rails to work I had to fix it first](https://github.com/rspec/rspec-rails/issues/1600).

**Comment by chrishough** [comment]
@wbigal your fix worked for me.  Can we add that to the documentation?

**Comment by wbigal** [comment]
It would be cool, @chrishough !

**Comment by sistemascreatix** [comment]
Using RoR 4.2.6
this works for me.
```ruby
group :test do
  gem 'test-unit', '~> 3.2'
  gem 'shoulda', '~> 3.5'
end
```

**Comment by sistemascreatix** [comment]
Using RoR 4.2.6
this works for me.
```ruby
group :test do
  gem 'test-unit', '~> 3.2'
  gem 'shoulda', '~> 3.5'
end
```

**Comment by MMcCormick** [comment]
@collimarco's [solution](https://github.com/thoughtbot/shoulda/issues/203#issuecomment-87406495) worked for me. I don't understand why the require would work here, and not `spec_helper.rb`, but it solved my issue.

> `require 'shoulda/matchers'`
> should go after
> `require 'rspec/rails'`
> in rails_helper.rb(not at the top of spec_helper.rb).

**Comment by dladowitz** [comment]
The solution @collimarco posted worked for me. 

require 'shoulda/matchers'
should go after

require 'rspec/rails'
in rails_helper.rb(not at the top of spec_helper.rb).

**Comment by jerelmiller** [comment]
I was able to get this to work using

```ruby
RSpec.configure do |config|
  # ...
  config.infer_spec_type_from_file_location!
end
```

It seems shoulda-matchers did not automatically add it if it didn't know it was a model test.

**Comment by ivyr** [comment]
@juniormesquitadandao Thanks your solution worked for me:
by updating the Gemfile
adding configuration for spec/shoulda_matchers_helper.rb
and requiring it in spec/rails_helper

**Comment by horozco** [comment]
Thanks @DonGiulio

**Comment by onetakeone** [comment]
Check https://github.com/thoughtbot/shoulda-matchers for configuration block to place in rails_helper.rb
